export const Kinks = [
  "fingering vaginas",
  "missionary (position)",
  "cunnilingus",
  "gags",
  "teeth",
  "ugliness",
  "plushies",
  "belches",
  "catching diseases",
  "armpits",
  "saliva",
  "facefucking",
  "teens under 18",
  "CGL",
  "pain (giving)",
  "pain (receiving)",
  "giving sexual workship",
  "receiving sexual worship",
  "anal sex",
  "unused condoms",
  "sploshing",
  "multiple partners",
  "facials",
  "being eagerly begged",
  "dirty clothes",
  "jawlines",
  "69",
  "cuddling",
  "romance",
  "strip teases",
  "destructive pregnancies",
  "toothlessness",
  "sister-brother incest",
  "sexual training (as trainer)",
  "sexual training (receiving)",
  "pegging",
  "exhibitionism",
  "sexual frustration",
  "dragons",
  "pumps (toy)",
  "noses",
  "tickling",
];
