export const Kinks = [
  "69",
  "age gap",
  "aliens",
  "anal hooks",
  "anal sex",
  "androgyny",
  "armpits",
  "ass-to-mouth",
  "babies/toddlers",
  "bears/lions",
  "begging",
  "being a master",
  "being a slave",
  "being dominant",
  "being eagerly begged",
  "being submissive",
  "belches",
  "bellies",
  "blindbolds",
  "blowjobs",
  "branding",
  "breast implants",
  "breast milk",
  "breeding",
  "bukkake",
  "burning",
  "calves",
  "catching diseases",
  "cats",
  "CGL",
  "crushing live creatures",
  "cuckoldry",
  "cuddling",
  "cunnilingus",
  "damaging/impalement",
  "destructive pregnancies",
  "diapers",
  "diapers",
  "dirtiness",
  "dirty clothes",
  "dirty clothes",
  "doctors",
  "dragons",
  "eager service",
  "escors/prostitutes",
  "excessive body hair",
  "executions",
  "exhibitionism",
  "extreme pain",
  "facefucking",
  "facials",
  "father-son incest",
  "feet",
  "fingering vaginas",
  "food",
  "free use society",
  "full time power dynamics",
  "gags",
  "gags",
  "ghosts",
  "giving sexual workship",
  "goats/sheep",
  "guns",
  "hair pulling",
  "hair",
  "hands",
  "hands",
  "hermaphrodites",
  "heroin",
  "horns/fangs",
  "horses",
  "hypnotism",
  "infibulation",
  "insults",
  "jawlines",
  "kidnapping",
  "light bondage",
  "light spanking",
  "lips",
  "maggots/flies",
  "medical horror",
  "medium bondage",
  "men with breasts",
  "mental disabilities",
  "meth",
  "missionary (position)",
  "MLP",
  "mother-daughter incest",
  "mother-son incest",
  "multiple partners",
  "multiple partners",
  "nazis",
  "necks",
  "noses",
  "nuns",
  "octopi/squid",
  "orcs/golems",
  "pain (giving)",
  "pain (receiving)",
  "partner swapping",
  "pegging",
  "penetrating an animal",
  "penile implants",
  "performing oral sex on an animal",
  "pigs",
  "plushies",
  "pre-puberty children",
  "pregnancy",
  "pubic hair",
  "pumps (toy)",
  "pumps",
  "rapeplay (giving)",
  "rapeplay (receiving)",
  "receiving oral sex from animal",
  "receiving sexual worship",
  "rodents",
  "romance",
  "saliva",
  "saliva",
  "scarification",
  "scat",
  "sensory deprivation",
  "sex with your dead body",
  "sexual frustration",
  "sexual frustration",
  "sexual partners fighting over you",
  "sexual training (as trainer)",
  "sexual training (receiving)",
  "sissification",
  "sister-brother incest",
  "sister-sister incest",
  "slugs/worms",
  "slut humiliation",
  "small breasts",
  "smegma",
  "SPH",
  "sploshing",
  "squirting",
  "strip teases",
  "struggling",
  "students",
  "stuffing",
  "teens under 18",
  "teeth",
  "thighs",
  "tickling",
  "tongues",
  "toothlessness",
  "transforming (size)",
  "ugliness",
  "unused condoms",
  "urine",
  "very tiny penises",
  "very tiny people",
  "violating consent",
  "vomit",
  "vore",
  "voyeurism",
  "wardrobe malfuntions",
  "werewolves",
  "wings",
  "wings",
  "woman without breasts",
  "zombies",
];
