export const Kinks = [
  "69",
  "age gap (as older)",
  "age gap (as younger)",
  "airplanes/cars",
  "aliens",
  "amputations",
  "anal hooks",
  "anal pregnancy",
  "anal sex",
  "androgyny",
  "angels/demons",
  "animal-esque clothing",
  "armpits",
  "ASMR",
  "ass-to-mouth",
  "babies/toddlers",
  "babysitters",
  "bad ends",
  "bears/lions",
  "begging (self)",
  "being dominant",
  "being submissive",
  "belches",
  "bellies",
  "blindfolds",
  "blood",
  "blowjobs",
  "body horror",
  "body swapping",
  "branding",
  "breast implants",
  "breast milk",
  "breeding/impregnation",
  "brother-brother incest",
  "buildings",
  "bukkake",
  "burning",
  "calves (body part)",
  "cameltoe",
  "cannibalism/meatslaves",
  "castration",
  "catching diseases",
  "cats",
  "causing mild pain",
  "CGL",
  "cheating",
  "cheerleaders",
  "choking",
  "creepy people/creatures",
  "crossdressing",
  "crushing (live creatures)",
  "cuckoldry",
  "cuddling",
  "cunnilingus",
  "damaging impalement",
  "defilement",
  "deformations",
  "destructive pregnancies",
  "diapers",
  "dirtiness",
  "dirty clothes",
  "doctors",
  "doggystyle (position)",
  "dogs",
  "dolls",
  "dolphins/whales",
  "double penetration",
  "dragons",
  "drunkenness",
  "eager begging (other)",
  "eager service",
  "electricity (painful)",
  "enthusiastic consent",
  "escorts/prostitutes",
  "excessive body hair",
  "executions",
  "exhibitionism (other)",
  "exhibitionism (self)",
  "extreme bondage (giving)",
  "extreme bondage (receiving)",
  "extreme pain",
  "extreme plastic surgery",
  "facefucking",
  "facesitting",
  "facials",
  "farts",
  "father-daughter incest",
  "father-son incest",
  "feet",
  "fingering vaginas",
  "fish/sharks",
  "food",
  "freeuse society",
  "full time power dynamics",
  "furries",
  "gags",
  "ghosts",
  "giving sexual worship",
  "glasses (clothing)",
  "goats/sheep",
  "grandparent/grandchild incest",
  "gross insects",
  "guns",
  "gynecologists",
  "hair (head)",
  "hair pulling",
  "hands",
  "hermaphrodites",
  "heroin",
  "horns/fangs",
  "horses",
  "hotwifing",
  "humans with animal body parts",
  "hypnotism",
  "infibulation",
  "inflatables",
  "insects/spiders",
  "insults",
  "jawlines",
  "kidnapping",
  "knees",
  "latex",
  "light bondage (giving)",
  "light bondage (receiving)",
  "light spanking",
  "lips",
  "living insertions",
  "maids",
  "medical horror",
  "medium bondage (giving)",
  "medium bondage (receiving)",
  "men with breasts",
  "men with penis and vagina",
  "men with vaginas",
  "menstrual blood",
  "mental disabilities",
  "meth",
  "missionary (position)",
  "MLP",
  "monkeys/apes",
  "mother-daughter incest",
  "mother-son incest",
  "multiple partners",
  "nazis",
  "necks",
  "non-gratifying pain (giving)",
  "non-gratifying pain (receiving)",
  "noses",
  "nuns",
  "octopi/squid",
  "old people",
  "orcs/ogres/golems",
  "oversized body parts",
  "oviposition",
  "pain (giving)",
  "pain (receiving)",
  "parasites/leeches",
  "partner swapping",
  "pegging",
  "penetrating an animal",
  "penile implants",
  "performing oral sex on animal",
  "pigs",
  "plushies",
  "pony play",
  "pre-puberty children",
  "pregnancy",
  "pubic hair",
  "public humiliation (receiving)",
  "pumps (toy)",
  "rapeplay (giving)",
  "rapeplay (receiving)",
  "rapid age progression",
  "rapid age regression",
  "receiving oral sex from animal",
  "receiving penetration from animal",
  "receiving sexual worship",
  "reptiles/amphibians",
  "rodents",
  "romance",
  "rotting dead bodies",
  "saliva",
  "scarification",
  "scary people/creatures",
  "scat",
  "sensory deprivation",
  "severe obesity",
  "sex with your dead body",
  "sexual cartoons",
  "sexual frustration?",
  "sexual obedience training (as trainee)",
  "sexual obedience training (as trainer)",
  "sexual partners fighting over you",
  "shoulders",
  "sissification",
  "sister-brother incest",
  "sister-sister incest",
  "slave/master (as master)",
  "slave/master (as slave)",
  "sleeping sex",
  "slime/goo people",
  "slugs/snails/worms",
  "slut humiliation",
  "small penis humiliation",
  "smegma",
  "sploshing",
  "squirting",
  "statues/mannequins",
  "strip teases",
  "struggling",
  "students",
  "stuffing",
  "teachers/professors",
  "tearing clothes off",
  "teeth",
  "thighs",
  "tickling",
  "tongues",
  "toothlessness",
  "transforming (animals)",
  "transforming (gender)",
  "transforming (inanimate objects)",
  "transforming (size)",
  "ugliness",
  "under-18 teens",
  "unused condoms",
  "urine",
  "used condoms",
  "vampires",
  "very short people",
  "very tiny people",
  "violating consent (giving)",
  "violating consent (receiving)",
  "vomit",
  "vore (hard)",
  "vore (soft)",
  "voyeurism (other)",
  "voyeurism (self)",
  "wardrobe malfunctions",
  "werewolves",
  "wings",
  "women with a penis",
  "women with penis and vagina",
  "women without breasts",
  "woundfucking",
  "zombies",
];
